vim.keymap.set("n", "<leader>mi", ":MoltenInit python3<cr>")
vim.keymap.set("v", "<C-m>", "<cmd>MoltenEvaluateVisual<cr>")
vim.keymap.set("n", "<C-m>", "<cmd>MoltenReevaluateCell<cr>")
vim.keymap.set("n", "<leader>ml", "<cmd>MoltenEvaluateLine<cr>")
vim.keymap.set("n", "<leader>mn", "<cmd>MoltenNext<cr>")
vim.keymap.set("n", "<leader>mp", "<cmd>MoltenPrev<cr>")
vim.keymap.set("n", "<leader>md", "<cmd>MoltenDelete<cr>")
vim.keymap.set("n", "<leader>mi", "<cmd>MoltenInterrupt<cr>")
vim.keymap.set("n", "<leader>mr", "<cmd>MoltenRestart<cr>")
vim.keymap.set("n", "<leader>mo", ":noautocmd MoltenEnterOutput<CR>")
